---
- name: Run Docker compose
  community.docker.docker_compose:
    project_name: '{{ category_name }}-{{ service_name_stage }}'
    project_src: '{{ remote_dir_path }}/{{ service_name }}'
    scale: 'app={{ scale }}'
    recreate: never
    build: true
    remove_orphans: true
  environment: '{{ app_environment }}'
