version: '3.7'

services:
  traefik:
    image: 'traefik:v2.9'
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/etc/traefik/dynamic'
      - '--providers.file.watch=true'
      - '--entrypoints.web.address=:80'
#       - '--entrypoints.websecure.address=:443'
#       - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
#       - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
#       - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
#       - '--certificatesresolvers.le.acme.email=${ACME_EMAIL}'
#       - '--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json'
#       - '--certificatesresolvers.le.acme.tlschallenge=true'
    labels:
#       - 'traefik.http.routers.traefik.tls=true'
#       - 'traefik.http.routers.traefik.tls.certresolver=le'
      - 'traefik.http.routers.traefik.entrypoints=web'
    ports:
      - '80:80'
#       - '443:443'
    networks:
      - 'infrastructure-traefik'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/home/ansible/infrastructure/traefik/dynamic:/etc/traefik/dynamic:ro'
#       - './letsencrypt:/letsencrypt'
    restart: 'always'

networks:
  infrastructure-traefik:
    external: true
