category_name: services
service_name: gif-j-backend
service_name_stage: '{{ service_name }}-{{ STAGE }}'
remote_dir_path: /home/{{ ansible_user }}/{{ category_name }}/{{ STAGE }}

docker_network_create: true
docker_scaling_timeout: 7

app_environment:
  STAGE: '{{ STAGE }}'
  AWS_ACCESS_KEY_ID: '{{ AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '{{ AWS_SECRET_ACCESS_KEY }}'
  AWS_REGION: 'eu-central-1'
  S3_BUCKET_NAME: 'gifalot-{{ STAGE }}'
  SERVICE_NAME_STAGE: '{{ service_name_stage }}'
  PORT: '{{ PORT | default("3333") }}'
  CORS_ORIGINS: '{{ CORS_ORIGINS | default("https://dev.gifalot.com") }}'
  GOOGLE_RECAPTCHA_SECRET_KEY: '{{ GOOGLE_RECAPTCHA_SECRET_KEY }}'
  GIPHY_API_KEY: '{{ GIPHY_API_KEY }}'
  MAIL_USER: '{{ MAIL_USER }}'
  MAIL_PASSWORD: '{{ MAIL_PASSWORD }}'
  REDIS_HOST: '{{ REDIS_HOST | default("localhost") }}'
  REDIS_PORT: '{{ REDIS_PORT | default("6379") }}'
  REDIS_PASSWORD: '{{ REDIS_PASSWORD }}'
  MYSQL_HOST: '{{ MYSQL_HOST }}'
  MYSQL_USER: '{{ MYSQL_USER }}'
  MYSQL_DB: '{{ MYSQL_DB }}'
  MYSQL_PORT: '{{ MYSQL_PORT | default("3306") }}'
  MYSQL_PASSWORD: '{{ MYSQL_PASSWORD }}'
  JWT_ACCESS_TOKEN_SECRET: '{{ JWT_ACCESS_TOKEN_SECRET }}'
  JWT_REFRESH_TOKEN_SECRET: '{{ JWT_REFRESH_TOKEN_SECRET }}'
