category_name: services
service_name: gif-j-backend
service_name_stage: '{{ service_name }}-{{ STAGE }}'
remote_dir_path: /home/{{ ansible_user }}/{{ category_name }}/{{ STAGE }}

docker_network_create: true
docker_scaling_timeout: 7

app_environment:
  STAGE: '{{ STAGE }}'
  AWS_ACCESS_KEY_ID: '{{ AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '{{ AWS_SECRET_ACCESS_KEY }}'
  AWS_REGION: 'eu-central-1'
  S3_BUCKET_NAME: 'gifalot-{{ STAGE }}'
  SERVICE_NAME_STAGE: '{{ service_name_stage }}'
  PORT: '3333'
  GOOGLE_RECAPTCHA_SECRET_KEY: '{{ GOOGLE_RECAPTCHA_SECRET_KEY }}'
  GIPHY_API_KEY: '{{ GIPHY_API_KEY }}'
  MAIL_USER: '{{ MAIL_USER }}'
  MAIL_PASSWORD: '{{ MAIL_PASSWORD }}'
  REDIS_HOST: '{{ service_name_stage }}-redis'
  REDIS_PORT: '6379'
  REDIS_PASSWORD: '{{ REDIS_PASSWORD }}'
  POSTGRES_HOST: '{{ service_name_stage }}-postgres'
  POSTGRES_USER: '{{ POSTGRES_USER }}'
  POSTGRES_DB: '{{ POSTGRES_DB }}'
  POSTGRES_PORT: '5432'
  POSTGRES_PASSWORD: '{{ POSTGRES_PASSWORD }}'
  JWT_ACCESS_TOKEN_SECRET: '{{ JWT_ACCESS_TOKEN_SECRET }}'
  JWT_REFRESH_TOKEN_SECRET: '{{ JWT_REFRESH_TOKEN_SECRET }}'
